# Hello! Please keep "Metrics" enabled unless you suffer from performance issues. This information is SUPER useful
# as a plugin developer and I would appreciate if it's kept enabled :) Thank you!

Metrics: true
PerformUpdateChecks: true

Keys:
  Unsmithed:
    ModelData: 1
    RecipeYield: 1
  Smithed:
    ModelData: 2
  AllowKeyDuplication: true
  AllowKeyMerging: true
  AllowKeyResetting: true

LockableBlocks:
- 'minecraft:chest'
- 'minecraft:trapped_chest'
- 'minecraft:acacia_trapdoor'
- 'minecraft:acacia_door'
- 'minecraft:acacia_fence_gate'
- 'minecraft:birch_trapdoor'
- 'minecraft:birch_door'
- 'minecraft:birch_fence_gate'
- 'minecraft:dark_oak_trapdoor'
- 'minecraft:dark_oak_door'
- 'minecraft:dark_oak_fence_gate'
- 'minecraft:jungle_trapdoor'
- 'minecraft:jungle_door'
- 'minecraft:jungle_fence_gate'
- 'minecraft:oak_trapdoor'
- 'minecraft:oak_door'
- 'minecraft:oak_fence_gate'
- 'minecraft:spruce_trapdoor'
- 'minecraft:spruce_door'
- 'minecraft:spruce_fence_gate'