Locale: en_CA
MetricsEnabled: true
RecipeYields: 1
DataSaveIntervalTicks: 6000
MaximumLocks:
  YOUR_WORLD: -1

Griefing:
  PreventLockedExplosions: true
  IgnorelocksCanBreakLocks: true
  OwnerRequiresKey: true

Aesthetics:
  DisplayLockedSmokeParticle: true
  
LockableBlocks:
- CHEST
- TRAPPED_CHEST
- TRAP_DOOR
- FURNACE
- DISPENSER
- DROPPER
- HOPPER
- WOODEN_DOOR
- ACACIA_DOOR
- BIRCH_DOOR
- DARK_OAK_DOOR
- JUNGLE_DOOR
- SPRUCE_DOOR
- FENCE_GATE
- ANVIL